begin;
select plan(12);
select has_table('public','professionals','professionals existe');
select row_security_active('public.professionals');
select has_policy('public','professionals','professionals_select_own');
select has_policy('public','professionals','professionals_insert_own');
select has_table('public','appointments','appointments existe');
select row_security_active('public.appointments');
select has_policy('public','appointments','appointments_select_own');
select has_policy('public','appointments','appointments_insert_own');
select has_table('public','treatments','treatments existe');
select row_security_active('public.treatments');
select has_policy('public','treatments','treatments_select_own');
select has_policy('public','treatments','treatments_insert_own');
select * from finish();
rollback;
