import { Link, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import type { CareAppointment } from '@bemmecuida/domain';
import { useAuth } from '@/auth/AuthProvider';
import { AppText } from '@/components/AppText';
import { BackHeader } from '@/components/BackHeader';
import { PrimaryButton } from '@/components/PrimaryButton';
import { Screen } from '@/components/Screen';
import { SecondaryButton } from '@/components/SecondaryButton';
import { Surface } from '@/components/Surface';
import { listAppointments, updateAppointmentStatus } from '@/data/treatment-repository';
import { useSync } from '@/sync/SyncProvider';
import { colors, radius, spacing } from '@/theme/tokens';
function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
export default function AppointmentsScreen(){const{session}=useAuth();const sync=useSync();const[items,setItems]=useState<CareAppointment[]>([]);const load=useCallback(async()=>{if(session)setItems(await listAppointments(session.user.id))},[session]);useFocusEffect(useCallback(()=>{void load()},[load,sync.lastSuccessAt]));async function changeStatus(item:CareAppointment,status:'completed'|'cancelled'){if(!session)return;try{await updateAppointmentStatus(session.user.id,item.id,status);await load();void sync.syncNow()}catch{Alert.alert('Não foi possível atualizar','Tente novamente.')}}const upcoming=items.filter(item=>item.status==='scheduled'&&item.startsAt>=new Date().toISOString()).reverse();const past=items.filter(item=>!upcoming.some(up=>up.id===item.id));return <Screen><BackHeader eyebrow="CONSULTAS" title="Agenda de cuidado e acompanhamento" titleTestID="appointments-title"/><Link href="/appointments/new" asChild><Pressable testID="appointments-add" accessibilityRole="button" style={styles.addButton}><AppText variant="bodyStrong" style={styles.addText}>+ Nova consulta</AppText></Pressable></Link><AppText variant="h2" style={styles.sectionTitle}>Próximas</AppText>{upcoming.length?upcoming.map(item=><Surface key={item.id} style={styles.card}><AppText variant="bodyStrong">{item.title}</AppText><AppText muted>{formatDate(item.startsAt)}</AppText>{item.location?<AppText variant="caption" muted>{item.location}</AppText>:null}<View style={styles.actions}><View style={styles.flex}><SecondaryButton label="Cancelar registro" onPress={()=>void changeStatus(item,'cancelled')}/></View><View style={styles.flex}><PrimaryButton label="Marcar realizada" onPress={()=>void changeStatus(item,'completed')}/></View></View></Surface>):<Surface><AppText muted>Nenhuma consulta futura cadastrada.</AppText></Surface>}<AppText variant="h2" style={styles.sectionTitle}>Histórico</AppText>{past.map(item=><Surface key={item.id} style={styles.card}><View style={styles.rowBetween}><View style={styles.flex}><AppText variant="bodyStrong">{item.title}</AppText><AppText variant="caption" muted>{formatDate(item.startsAt)}</AppText></View><View style={styles.badge}><AppText variant="caption">{item.status==='completed'?'Realizada':item.status==='cancelled'?'Cancelada':'Agendada'}</AppText></View></View></Surface>)}</Screen>}
const styles=StyleSheet.create({addButton:{minHeight:52,alignItems:'center',justifyContent:'center',backgroundColor:colors.primarySoft,borderRadius:radius.md},addText:{color:colors.primaryStrong},sectionTitle:{marginTop:spacing.xl,marginBottom:spacing.md},card:{gap:spacing.sm,marginBottom:spacing.md},actions:{flexDirection:'row',gap:spacing.md,marginTop:spacing.sm},flex:{flex:1},rowBetween:{flexDirection:'row',alignItems:'center',gap:spacing.md},badge:{borderRadius:radius.pill,backgroundColor:colors.sand,paddingHorizontal:spacing.md,paddingVertical:spacing.xs}});
